### ISSUE TITLE
Possible Tag issue

### ISSUE THREAD

**Issue by piebaker** [FinnSetchell/MoogsEndStructures#2]
Using LoadMyFingTags an error is pointed out:

`Couldn't load certain entries with the tag mes:common_avoid: mes:tower (from Moog's End Structures), mes:decoration (from Moog's End Structures)`

Attempting to locate these structures their tags are missing

Apparently, these tags may be broken, is it safe to ignore this, or worth looking into further?

**Comment by xR4YM0ND** [comment]
Same Error here:
```js
[Worker-ResourceReload-14/ERROR]: Couldn't load tag mes:common_avoid as it is missing following references: mes:tower (from fabric), mes:decoration (from fabric)
```

Fabric 1.20.1
Loader 0.15.9

Code line 1312
[latest.log](https://gist.github.com/xR4YM0ND/2a994cd0582b26d6d0729432a872fc92#file-latest-log-L1312)

**Comment by FinnSetchell** [comment]
fixed in next release
