### ISSUE TITLE
1.20.1 Compatibility with Blueprint

### ISSUE THREAD

**Issue by madio919** [FinnSetchell/MoogsEndStructures#6]
There's some sort of issue between the newest version of blueprint and this mod. It was reported in the Outer End mod and fixed, but something is still off here. I can't start my server without rolling back blueprint and the Outer End (or deleting this mod).

Thread from Outer End: https://github.com/BlueDuckYT/The-Outer-End/issues/89 

[crash-2024-03-08_20.20.03-server.txt](https://github.com/FinnSetchell/MoogsEndStructures/files/14542934/crash-2024-03-08_20.20.03-server.txt)

**Comment by FinnSetchell** [comment]
this should be fixed for the next release
